server:
  port: 8000

spring:
  application:
    name: ide-project
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8849
        cluster-name: Suzhou
  devtools:
    livereload:
      enabled: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/web_ide?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
  jackson:
    time-zone: GMT+8
    # 日期格式设置
    date-format: yyyy-MM-dd HH:mm:ss



  #关闭thymeleaf缓存 开发期间就能看到实时效果；上线以后就要打开缓存了(效果不大)
  web:
    resources:
      static-locations: classpath:/static/

#  #整合Spring Session 指定session是存到redis里
#  session:
#    store-type: redis
#  #配置Zipkin链路追踪可视化展示
#  zipkin:
#    base-url: http://192.168.56.10:9411/
#    #关闭自己的服务发现功能
#    discovery-client-enabled: true
#    sender:
#      #设置采用http的方式
#      type: web
#  sleuth:
#    sampler:
#      #配置sleuth采样器 100%
#      probability: 1
#

##management.endpoints.web.exposure.include=*
#配置actuator统计审计信息 配合sentinel
management:
  endpoints:
    web:
      exposure:
        include: all

##开启feign sentinel 熔断保护
#feign:
#  sentinel:
#    enabled: true