server:
  port: 88

spring:
  application:
    name: ide-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8849
        cluster-name: Suzhou     # 集群名
    gateway:
      routes:
        - id: project-route
          uri: lb://ide-project
          predicates:
            - Path=/api/ide/**  # 以 /api/ide/ 开头
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://ide-admin
          predicates:
            - Path=/api/sys/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
management:
  endpoints:
    web:
      exposure:
        include: all
feign:
  client:
    config:
      default:
        logger-level: basic
  httpclient:
    enabled: true  # 支持 httpclient 连接池
    max-connections: 200   # 最大的连接数
    max-connections-per-route: 50   # 每个路径最大的连接数
